# Basement entrance light switch

- alias: Toggle basement entrance downlights
  trigger:
    platform: mqtt
    topic: "push_buttons/basement_entrance_1/toggle"
  action:
    service: light.toggle
    entity_id: light.basement_entrance_downlights

- alias: Toggle basement entrance downlights
  trigger:
    platform: mqtt
    topic: "push_buttons/basement_entrance_2/toggle"
  action:
    service: light.toggle
    entity_id: light.basement_entrance_wall_recessed

- alias: Toggle basement hall downlights
  trigger:
    platform: mqtt
    topic: "push_buttons/basement_entrance_3/toggle"
  action:
    service: light.toggle
    entity_id: light.basement_hall_downlights

- alias: Toggle staircase basement hall
  trigger:
    platform: mqtt
    topic: "push_buttons/basement_entrance_4/toggle"
  action:
    service: light.toggle
    entity_id: light.staircase_basement_hall

- alias: Toggle outdoor LED strip basement
  trigger:
    platform: mqtt
    topic: "push_buttons/basement_entrance_5/toggle"
  action:
    service: light.toggle
    entity_id: light.outdoor_basement_led_strip

# Basement practice entrance

- alias: Toggle practice entrance downlights
  trigger:
    platform: mqtt
    topic: "push_buttons/practice_1/toggle"
  action:
    service: light.toggle
    entity_id: light.practice_entrance_downlights

- alias: Toggle practice desk downlight
  trigger:
    platform: mqtt
    topic: "push_buttons/practice_2/toggle"
  action:
    service: light.toggle
    entity_id: light.practice_desk_downlight

- alias: Toggle practice desk downlight
  trigger:
    platform: mqtt
    topic: "push_buttons/practice_3/toggle"
  action:
    service: light.toggle
    entity_id: group.practice_central_downlights

# Basement practice exit

- alias: Toggle practice entrance downlights
  trigger:
    platform: mqtt
    topic: "push_buttons/practice_exit_1/toggle"
  action:
    service: light.toggle
    entity_id: light.practice_entrance_downlights

- alias: Toggle practice desk downlight
  trigger:
    platform: mqtt
    topic: "push_buttons/practice_exit_2/toggle"
  action:
    service: light.toggle
    entity_id: light.practice_desk_downlight

- alias: Toggle practice desk downlight
  trigger:
    platform: mqtt
    topic: "push_buttons/practice_exit_3/toggle"
  action:
    service: light.toggle
    entity_id: group.practice_central_downlights

# Basement hall

- alias: Toggle basement hall downlights from staircase
  trigger:
    platform: mqtt
    topic: "push_buttons/basement_staircase_1/toggle"
  action:
    service: light.toggle
    entity_id: light.basement_hall_downlights

- alias: Toggle staircase lights from basement
  trigger:
    platform: mqtt
    topic: "push_buttons/basement_staircase_2/toggle"
  action:
    service: light.toggle
    entity_id: light.staircase_basement_hall

# Tech room

- alias: Toggle light tech room
  trigger:
    platform: mqtt
    topic: "push_buttons/tech_room_1/toggle"
  action:
    service: light.toggle
    entity_id: light.tech_room_central

# Storage room

- alias: Toggle light storage room from storage room
  trigger:
    platform: mqtt
    topic: "push_buttons/storage_1/toggle"
  action:
    service: light.toggle
    entity_id: light.storage_room_central

# Night hall

- alias: Toggle night hall central light
  trigger:
    platform: mqtt
    topic: "push_buttons/night_hall_1/toggle"
  action:
    service: light.toggle
    entity_id: light.night_hall_central
