version: "3"
services:
  homeassistant:
    image: homeassistant/home-assistant
    restart: always
    volumes:
      - ./:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    depends_on:
      - mosquitto
      - tor
  mosquitto:
    image: eclipse-mosquitto
    network_mode: host
  tor:
    image: osminogin/tor-simple
    network_mode: host
    volumes:
      - ./torrc:/etc/tor/torrc
