# Second floor
- platform: mqtt
  name: "Night hall central"
  command_topic: "lights/night_hall_central/switch"
- platform: mqtt
  name: "Night hall downlights"
  command_topic: "lights/night_hall_downlights/switch"
- platform: mqtt
  name: "Night hall toilet"
  command_topic: "lights/night_hall_toilet/switch"
- platform: mqtt
  name: "Bath room entrance"
  command_topic: "lights/bath_room_entrance/switch"
- platform: mqtt
  name: "Bath room bath"
  command_topic: "lights/bath_room_bath/switch"
- platform: mqtt
  name: "Bath room shower"
  command_topic: "lights/bath_room_shower/switch"
- platform: mqtt
  name: "Bath room closet"
  command_topic: "lights/bath_room_closet/switch"
- platform: mqtt
  name: "Bedroom parents left downlights"
  command_topic: "lights/bedroom_parents_left_downlights/switch"
- platform: mqtt
  name: "Bedroom parents central"
  command_topic: "lights/bedroom_parents_central/switch"
- platform: mqtt
  name: "Bedroom parents right downlights"
  command_topic: "lights/bedroom_parents_right_downlights/switch"
- platform: mqtt
  name: "Bedroom parents dressing"
  command_topic: "lights/bedroom_parents_dressing/switch"
- platform: mqtt
  name: "Bedroom Victor central"
  command_topic: "lights/bedroom_victor_central/switch"
- platform: mqtt
  name: "Bedroom Lucas central"
  command_topic: "lights/bedroom_lucas_central/switch"
