- id: toggle_night_hall_central
  alias: Toggle night hall central light
  trigger:
    platform: mqtt
    topic: "push_buttons/night_hall_central_1/toggle"
  action:
    service: light.toggle
    entity_id: light.night_hall_central
