- id: toggle_night_hall_switch
  alias: Switch MQTT light based on toggle
  trigger:
    platform: mqtt
    topic: "night_hall/toggle"
    payload: "trigger"
  action:
    service: light.toggle
    entity_id: light.floor_hall_central_light
